Newsweek clone with Bootstrap
len23/news-week-bootstrap pull request #2
Opened 2020-09-04 17:02 UTC by len23

For this project we used:
- HTMLl5 and CSS3
- Bootstrap v.4.5
- Responsive Design
- Media Queries

2020-09-04 20:19 UTC, SafaErden requested changes
## Status: Require changes ♻️

**Hi TEAM, your project is awesome and it really looks exactly like the original. 👐 However, we need a little fix before we can proceed. Kindly find the comments below**
##

**REQUIRED CHANGES**

- [x] Please implement the proper bootstrap classes to make the navbar fixed when the user scrolls down. 

![image](https://user-images.githubusercontent.com/60184961/92280916-2ac95780-ef03-11ea-949e-1b22bc0a2a49.png)

- [x] There is not enough space below the footer. Please apply proper bootstrap classes to add some space below the footer.

![image](https://user-images.githubusercontent.com/60184961/92281128-a4614580-ef03-11ea-98f2-9de1cc6c63d9.png)

- [x] The line below the Newsweek logo is missing. Please kindly fix it.

![image](https://user-images.githubusercontent.com/60184961/92281181-bd69f680-ef03-11ea-82b7-60ba9a908f1d.png)

- [x] Labels are missing some images. Please add them.

![image](https://user-images.githubusercontent.com/60184961/92281651-b394c300-ef04-11ea-87cd-f4099a81ff03.png)

- Additional required changes are listed below, please kindly check them.

##

**SUMMARY**

As I mentioned above, your project is almost done. You have some minor issues to solve. Please be an optimist and do not forget that the main purpose is to learn and practice. Do not let the requested changes discourage you 👍

##

*Kindly make the changes and submit another code review when you are ready*


Questions or comments? Reach me on [Twitter](https://twitter.com/safaerden) or [LinkedIn](https://www.linkedin.com/in/safaerden/)

Happy coding_ 👨‍💻 

**Safa ERDEN**

2020-09-04 20:19 UTC, SafaErden commented on README.md
> +- Linkedin: [linkedin](www.linkedin.com/in/Nexch)
- [x] Since the way you implement a link to your README is wrong, this link is broken:
![image](https://user-images.githubusercontent.com/60184961/92272390-1fb9fb80-eef2-11ea-9412-41b9f54a7635.png)

You should add https:// before the link you want to implement.

Please fix it.

2020-09-04 20:19 UTC, SafaErden commented on index.html
> +        <ul class="navbar-nav d-flex justify-content-between w-100  ">
- [x] The sub-navigation links overflow the main content in medium screen size, creates redundant empty space on the right side, and causes redundant horizontal scroll bar. Please fix it to be responsive depending on the different screen sizes.
![image](https://user-images.githubusercontent.com/60184961/92278650-58f86880-eefe-11ea-9fae-eb7120d39630.png)

- [x] Also the background color of the sub-navigation links should be white bu in your project the bg is gray. Please kindly fix it to create the same UI with the original page.

2020-09-04 20:19 UTC, SafaErden commented on index.html
> +
- [OPTIONAL ] I can suggest you use any code-formatter to avoid redundant spaces and empty lines which makes your code look messy.

2020-09-04 20:19 UTC, SafaErden commented on index.html
> +              <h2 class="text-secondary">Feature Stories</h2>
- [x] You have one typo here, it is supposed to be 'FEATURED STORIES'.

2020-09-04 20:19 UTC, SafaErden commented on index.html
> +      <div class="col px-4 px-lg-0">
- [x] Header of the debate section is missing, please kindly add it.

2020-09-04 20:19 UTC, SafaErden commented on index.html
> +        <div class="card mb-3 border-left-0 border-right-0">
- [ ] The versus line is missing, or not implemented properly. Please implement it properly to create the same UI with the original page.

![image](https://user-images.githubusercontent.com/60184961/92280647-8b0bc980-ef02-11ea-925e-63a0de5b180a.png)

2020-09-04 20:19 UTC, SafaErden commented on index.html
> +          <img src="./images/florida-polytechnic-university.jpg" class="card-img-top rounded-0" alt="news-image">
- [ ] This image link is broken. Please fix it.
![image](https://user-images.githubusercontent.com/60184961/92280715-b55d8700-ef02-11ea-813d-31ad19320a92.png)

2020-09-04 20:19 UTC, SafaErden commented on styles/styles.css
> +}
- [ ] Please consider using Bootstrap CSS classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) from [Pathwrigth](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/)) if it is possible.

2020-09-04 20:19 UTC, SafaErden commented on styles/styles.css
> +}
- [ ] Please consider using Bootstrap CSS classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) from [Pathwrigth](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/)) if it is possible.

2020-09-04 20:19 UTC, SafaErden commented on styles/styles.css
> +}
- [ ] Please consider using Bootstrap CSS classes **everywhere** for styling (for example [Grid layout](https://getbootstrap.com/docs/4.3/layout/overview/) and [Flex](https://getbootstrap.com/docs/4.3/layout/utilities-for-layout/#flexbox-options)) ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/html_css/using_bootstrap/bootstrap_classes_requirement.png) from [Pathwrigth](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/59540308/)) if it is possible.

2020-09-05 00:38 UTC, elmejdki requested changes
# status: require changes :recycle: 
## Well you have done an impressive work on this project :clap: :+1: :100:  but in order to get it approved :checkered_flag: we need to put more work on it :hammer: :wrench: :toolbox:.

- [x] The header should take 100% of the max-width, also the remained space should be colored with a gray color:

| *Clone* | *Original* |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92292374-d202ba80-ef14-11ea-9337-5c7b055acb19.png) | ![image](https://user-images.githubusercontent.com/34653764/92292381-e5ae2100-ef14-11ea-8dcc-26d606ac84bc.png) |

- [x] the headers are too big you need to make them smaller as in the original:
![image](https://user-images.githubusercontent.com/34653764/92292464-49d0e500-ef15-11ea-9c84-a72d29e9320e.png)

- [ ] article titles should be bold and also should be warped by an anchor tag, same for article images.

- [x] the debate and features stories columns should have the same width size.

| *Clone* | *Original* |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92292571-c237a600-ef15-11ea-9577-288688da7710.png) | ![image](https://user-images.githubusercontent.com/34653764/92292579-d085c200-ef15-11ea-8c26-101d9723d09f.png) |

- [x] the debate circled images should have the same size, you can see clearly that the second image is smaller than the first one, the difference is more clear on the tablet view:

![image](https://user-images.githubusercontent.com/34653764/92292596-eabfa000-ef15-11ea-8c9f-baa621ad3b71.png)

*Tablet view* :point_down: :point_down: :point_down:
![image](https://user-images.githubusercontent.com/34653764/92292664-50ac2780-ef16-11ea-8dcf-94d123ef6f2e.png)


- [x] on the tablet view the debate section should take 100% of the width, also the opinion images should be smaller:

| *Clone* | *Original* |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92292733-9d8ffe00-ef16-11ea-9d3e-de2c5d9176e7.png) | ![image](https://user-images.githubusercontent.com/34653764/92292718-8fda7880-ef16-11ea-9f21-a14e28a26517.png) |

- [x] on tablet view adjust this form to the same size as in the original:

| *Clone* | *Original* |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92292785-d16b2380-ef16-11ea-9f96-d04ddcb80f78.png) | ![image](https://user-images.githubusercontent.com/34653764/92292760-bef0ea00-ef16-11ea-83c9-9f010166b280.png) |

- [ ] the images on the right are really small resize them to match the original:

| *Clone* | *Original* |
|:---:|:---:|
| ![image](https://user-images.githubusercontent.com/34653764/92292827-23ac4480-ef17-11ea-8758-f3d40d082ff4.png) | ![image](https://user-images.githubusercontent.com/34653764/92292836-37f04180-ef17-11ea-911b-c8a1370b6f92.png) |

- [ ] remove the empty div's from the header, I suggest to use *display: none*;

![image](https://user-images.githubusercontent.com/34653764/92292872-64a45900-ef17-11ea-82c7-0e6cb72f6f58.png)

- [ ] on mobile view, fix the debate section images:
![image](https://user-images.githubusercontent.com/34653764/92292905-9ddcc900-ef17-11ea-9985-24789fb9f98f.png)

- [ ] one the opinion section align the images with the text correctly:
![image](https://user-images.githubusercontent.com/34653764/92292917-b3ea8980-ef17-11ea-8aad-b0e87e064bdb.png)

- [ ] you have a typo in your buttons kindly fix it:
![image](https://user-images.githubusercontent.com/34653764/92292937-ca90e080-ef17-11ea-8232-e066c90cc713.png)


- [ ] Fix the size of the Newsweek logo in the magazine and editor's pick titles:
![image](https://user-images.githubusercontent.com/34653764/92292960-e1cfce00-ef17-11ea-8d4a-3b034876883f.png)

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

2020-09-07 16:25 UTC, MuriloRoque requested changes
# Changes requested :red_circle: 

### Hello @len23 and @Nexch :wave: 

### You have done an awesome job, your page is great, definitely one of the best I saw :grin: There is just one little issue we need to fix. I don't know if it happened after the last review or not, but I just can't let it be like this :grimacing: 

- [x] In Tablet and Mobile views, your headings (i.e.: 'Top Story') don't appear in the top, check my screenshots below:

![Screenshot from 2020-09-07 13-21-23](https://user-images.githubusercontent.com/59691171/92406058-73546100-f10d-11ea-9417-a4f99646ceaa.png)
<br>

![Screenshot from 2020-09-07 13-21-27](https://user-images.githubusercontent.com/59691171/92406065-77807e80-f10d-11ea-8393-a3d48b002c33.png)
<br>

### Kindly make the requested changes and submit for another review, please :pray: 

### I will be on Slack 24/7 in case you have any questions about this review :handshake: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-07 16:27 UTC, MuriloRoque commented
Sorry, I meant Tablet and Mobile views, I just edited it :+1:

2020-09-07 16:34 UTC, MuriloRoque approved these changes
# Status: Approved :green_circle: 

### Hello again @len23 and @Nexch :wave: 

### Thank you for making all of the required changes, your project is approved :clap: :clap: :clap: 

### You may merge, good luck with your next projects :rocket: 

Murilo Roque Paiva da Silva

- Github: [@muriloroque](https://github.com/MuriloRoque)
- Linkedin: [MuriloRoque](https://www.linkedin.com/in/murilo-roque-b1268741/)

[![Twitter Follow](https://img.shields.io/twitter/follow/MuriloRoquePai1?label=Follow%20Murilo%20on%20Twitter&style=social)](https://twitter.com/MuriloRoquePai1)

2020-09-07 16:37 UTC, merged